- name: install btrfs-tools
  apt: name=btrfs-tools state=latest

- name: create docker mountpoint
  file: name=/var/lib/docker state=directory

- name: create docker fs
  filesystem:
    dev: "{{ docker_dev }}"
    fstype: btrfs

- name: create directory for ansible custom facts
  file: state=directory recurse=yes path=/etc/ansible/facts.d

- name: create fact for docker fs blkid
  template:
    src: etc/ansible/facts.d/docker_blkid.fact
    dest: /etc/ansible/facts.d/docker_blkid.fact
    mode: 500

- name: re-read facts after adding custom fact
  setup: filter=ansible_local

- name: mount docker fs
  mount:
    src: UUID={{ ansible_local.docker_blkid }}
    name: /var/lib/docker
    fstype: btrfs
    state: mounted
  notify: restart docker

- name: install docker
  apt: name=docker.io state=latest default_release=jessie-backports

- name: start docker
  service: name=docker state=started enabled=true

- name: install python-docker
  apt: name=python-docker state=latest default_release=sid

- name: generate container config dir
  file: state=directory recurse=yes path=/etc/container_environment
