# vim: set ft=ansible
---

webproxy:
  image: nginx
  version: latest
  service_name: "{{ webproxy_service_name }}"
  configs: /etc/webproxy/sites
  certs: /etc/webproxy/certs
  logs: /var/log/webproxy
  static: /var/www

proxy_sites:
  - server_name: caldav.losinski.de
    target:
      service: davical
      host: davical
      port: 80
    template: caldav.conf.j2
  - server_name: box.losinski.de
    content:
      name: box_content
      source: www/dummy/
    template: box.conf.j2
    proxy:
      - location: caldav_server
        host: davical
        port: 80

