# vim: set ft=yaml sw=2 expandtab ts=2:
---
- hosts: box-ng
  remote_user: root
  vars:
    apt_mirror: http://ftp.de.debian.org/debian/
    apt_extra_dists:
      - { dist: unstable, prio: 150 }
      - { dist: experimental, prio: 145 }
    docker_dev: /dev/vda
    davical_backup_file: backup/caldav_dump.sql
  roles:
    - apt_config
    - common
    - docker_host
    - postgres_container
    - davical
    - nginx
