pg:
  version: 9.4
  image: postgres
  password: "{{ postgres_container_password }}"
  data_container: "postgres-data"
  service_name: "postgres"

postgres_container_image: "{{ pg.image }}:{{ pg.version }}"
