# vim: set ft=ansible
---
- name: generate hosts entries
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.name | replace('.', '\\.') }}"
    line: "{{ item.net | ipaddr('1') | ipaddr('address') }} {{ item.name }}"
  with_items: vpn.static_clients
