# vim: set ft=ansible:
---
- name: update system
  apt:
    update_cache: yes
    upgrade: safe

- name: install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - bash-completion
    - ncurses-term
    - fail2ban
    - python-pyinotify
    - etckeeper

- name: install extra packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mosh
    - tmux
    - htop
    - tcpdump
  when: default_extra_packages is defined


- name: copy base configs
  copy: src={{item.src}} dest={{item.dst}}
  with_items:
      - {src: etc/vim/vimrc.local, dst: /etc/vim/vimrc.local}
      - {src: root/dircolors-256, dst: /root/.dircolors-256}
      - {src: root/bashrc, dst: /root/.bashrc}
      - {src: root/tmux.conf, dst: /root/.tmux.conf}

- name: enable google DNS
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: "prepend domain-name-servers {{ enforce_dns_server | join(', ') }};"
    state: present
  when: enforce_dns_server is defined
