# vim: set ft=ansible:
---
- name: update system
  apt:
    update_cache: yes
    upgrade: safe

- name: install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - tmux
    - bash-completion
    - ncurses-term
    - htop
    - fail2ban
    - etckeeper

- name: copy base configs
  copy: src={{item.src}} dest={{item.dst}}
  with_items:
      - {src: etc/vim/vimrc.local, dst: /etc/vim/vimrc.local}
      - {src: root/dircolors-256, dst: /root/.dircolors-256}
      - {src: root/bashrc, dst: /root/.bashrc}
      - {src: root/tmux.conf, dst: /root/.tmux.conf}
