# vim: set ft=ansible:
---
- name: update system
  apt:
    update_cache: yes
    upgrade: safe

- name: install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mosh
    - vim
    - tmux
    - bash-completion
    - ncurses-term
    - htop
    - fail2ban
    - etckeeper
    - tcpdump

- name: copy base configs
  copy: src={{item.src}} dest={{item.dst}}
  with_items:
      - {src: etc/vim/vimrc.local, dst: /etc/vim/vimrc.local}
      - {src: root/dircolors-256, dst: /root/.dircolors-256}
      - {src: root/bashrc, dst: /root/.bashrc}
      - {src: root/tmux.conf, dst: /root/.tmux.conf}

- name: enable google DNS
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: "prepend domain-name-servers 8.8.8.8;"
    state: present
