- name: configure dist priorities
  template:
    src: etc/apt/preferences.d/dist_pinning.j2
    dest: /etc/apt/preferences.d/dist_pinning
  notify: update package list

- name: configure sources
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
  notify: update package list

- name: disable install recommend
  copy:
    src: etc/apt/apt.conf.d/06norecommends
    dest: /etc/apt/apt.conf.d/06norecommends

